language: generic 
sudo: required
servies: 
  - docker 

berfore_install:
  - docker build -t adrianhiu/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true adrianhiu/react-test npm run test

after_success:
  - docker build -t adrianhiu/mutli-client ./client
  - docker build -t adrianhiu/mutli-nginx ./nginx
  - docker build -t adrianhiu/mutli-server ./server
  - docker build -t adrianhiu/mutli-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push adrianhiu/mutli-client 
  - docker push adrianhiu/mutli-nginx 
  - docker push adrianhiu/mutli-server 
  - docker push adrianhiu/mutli-worker 
